# Writing the class (to move to a python file)

In [11]:
from sqlalchemy import create_engine, MetaData, Table
from sqlalchemy.engine.base import Connection, Engine
from sqlalchemy.sql.schema import Table as SQLTable
from sqlalchemy import text
import geopandas as gpd
import os
from dotenv import load_dotenv
from typing import List, Any


class DatabaseHandler:
    """
    A class to handle database operations using SQLAlchemy.
    """

    def __init__(self, db_url: str):
        """
        Initialize the DatabaseHandler with a database URL.

        :param db_url: The database URL
        """
        self.engine: Engine = create_engine(db_url)
        self.connection: Connection = self.engine.connect()
        self.metadata: MetaData = MetaData()
        self.metadata.reflect(bind=self.engine)

    def get_table_names(self) -> List[str]:
        """
        Get the names of all tables in the database.

        :return: A list of table names
        """
        return list(self.metadata.tables.keys())

    def get_table(self, table_name: str) -> SQLTable:
        """
        Get a specific table by name.

        :param table_name: The name of the table
        :return: The SQLAlchemy Table object
        """
        return Table(table_name, self.metadata, autoload_with=self.engine)

    def execute_sql(self, statement: str) -> List[Any]:
        """
        Execute an SQL statement and return the results.

        :param statement: The SQL statement to execute
        :return: The results of the query
        """
        try:
            result = self.connection.execute(text(statement))
            return result.fetchall()
        except Exception as e:
            print(f"An error occurred: {e}")
            return []
    
    def execute_geo_sql(self, statement: str) -> gpd.GeoDataFrame:
        """
        Execute an SQL statement and return the results as a GeoDataFrame.

        :param statement: The SQL statement to execute
        :return: The results of the query
        """
        # read the query results into a GeoDataFrame
        gdf = gpd.read_postgis(statement, con=self.engine)
        # return the GeoDataFrame
        return gdf

    def close_connection(self) -> None:
        """
        Close the database connection.
        """
        self.connection.close()

# Confirming the class can get initialized well

In [8]:
# Load environment variables from .env file
load_dotenv()

# Get username and password from environment variables
username = os.getenv('DB_USERNAME')
password = os.getenv('DB_PASSWORD')

# Create an instance of DatabaseHandler
db_handler = DatabaseHandler(f'postgresql://{username}:{password}@localhost:5432/field_mrv')

# Example usage
print(db_handler.get_table_names())
mytable = db_handler.get_table('locations')
print(mytable)

# Close the connection
db_handler.close_connection()

['spatial_ref_sys', 'locations', 'field_boundaries']
locations

/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'shape'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'location'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'service_area'
  self.metadata.reflect(bind=self.engine)

# Reading the data in

In [9]:
# Create an instance of DatabaseHandler
db_handler = DatabaseHandler(f'postgresql://{username}:{password}@localhost:5432/field_mrv')
#querying this table:
sql_statement = "SELECT * FROM locations"
results = db_handler.execute_sql(sql_statement)
print(results)

[(2, 'Fazenda Boa Vista', '0101000020E6100000F437A11001F747C00113B875378F2FC0', '0103000020E61000000100000005000000D5B2B5BE48F847C07C2766BD188A2FC012BD8C62B9F547C07C2766BD188A2FC012BD8C62B9F547C087FE092E56942FC0D5B2B5BE48F847C087FE092E56942FC0D5B2B5BE48F847C07C2766BD188A2FC0')]

/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'shape'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'location'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/3680573318.py:26: SAWarning: Did not recognize type 'geometry' of column 'service_area'
  self.metadata.reflect(bind=self.engine)

# reading in the data to geopandas

In [15]:
# Create an instance of DatabaseHandler
db_handler = DatabaseHandler(f'postgresql://{username}:{password}@localhost:5432/field_mrv')
location_table = db_handler.execute_geo_sql("Select id, name, service_area, location as geom from locations")
print(type(location_table))
location_table.head()

<class 'geopandas.geodataframe.GeoDataFrame'>

/tmp/ipykernel_307621/221027646.py:25: SAWarning: Did not recognize type 'geometry' of column 'shape'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/221027646.py:25: SAWarning: Did not recognize type 'geometry' of column 'location'
  self.metadata.reflect(bind=self.engine)
/tmp/ipykernel_307621/221027646.py:25: SAWarning: Did not recognize type 'geometry' of column 'service_area'
  self.metadata.reflect(bind=self.engine)

,id,name,service_area,geom
0,2,Fazenda Boa Vista,0103000020E61000000100000005000000D5B2B5BE48F8...,POINT (-47.92972 -15.77972)

In [17]:
field_boundary_table = db_handler.execute_geo_sql("""
    Select 
    boundary_id, 
    location_id,
    shape,
    area_hectares,
    crop_type,
    last_surveyed,
    soil_type,
    elevation_avg as geom 
    from field_boundaries 
    """)
print(type(field_boundary_table))
field_boundary_table.head()

<class 'geopandas.geodataframe.GeoDataFrame'>

,boundary_id,location_id,shape,area_hectares,crop_type,last_surveyed,soil_type,geom
0,3,2,0103000020E610000001000000050000000E677E3507F8...,25.7,Coffee,2025-01-03 13:21:51.208420,None,None
1,4,2,0103000020E610000001000000050000004A46CEC29EF6...,18.3,Sugarcane,2025-02-03 13:22:00.842088,None,None

# Joining the two tables together:

In [18]:
# Joining the location_table and field_boundary_table on the location_id column
joined_table = location_table.merge(field_boundary_table, left_on='id', right_on='location_id')
print(type(joined_table))
joined_table.head()

<class 'geopandas.geodataframe.GeoDataFrame'>

,id,name,service_area,geom_x,boundary_id,location_id,shape,area_hectares,crop_type,last_surveyed,soil_type,geom_y
0,2,Fazenda Boa Vista,0103000020E61000000100000005000000D5B2B5BE48F8...,POINT (-47.92972 -15.77972),3,2,0103000020E610000001000000050000000E677E3507F8...,25.7,Coffee,2025-01-03 13:21:51.208420,None,None
1,2,Fazenda Boa Vista,0103000020E61000000100000005000000D5B2B5BE48F8...,POINT (-47.92972 -15.77972),4,2,0103000020E610000001000000050000004A46CEC29EF6...,18.3,Sugarcane,2025-02-03 13:22:00.842088,None,None

# Visualizing

In [20]:
import matplotlib.pyplot as plt

joined_table.set_geometry('shape', inplace=True)
# Plot the joined_table data
fig, ax = plt.subplots(figsize=(10, 10))
joined_table.plot(ax=ax, column='crop_type', legend=True, cmap='Set2')

# Set plot title and labels
ax.set_title('Field Boundaries by Crop Type')
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')

plt.show()

TypeError: Input must be valid geometry objects: 0103000020E610000001000000050000000E677E3507F847C024EEB1F4A18B2FC02DEC6987BFF647C024EEB1F4A18B2FC02DEC6987BFF647C0A9D903ADC0902FC00E677E3507F847C0A9D903ADC0902FC00E677E3507F847C024EEB1F4A18B2FC0